
server:
  port: 9966
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gdtyg?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Fantomvip6!!
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false